# Generated by Django 4.0.8 on 2024-01-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='location',
        ),
    ]
