build-job:       # This job runs in the build stage, which runs first.
  image: docker/compose:latest
  stage: build
  script:
    - echo "Building and running docker..."
    - DOMAIN=tdt4237.idi.ntnu.no docker-compose up --build -d
  only:
    - production
