# Generated by Django 4.0.8 on 2023-10-07 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_manager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_moderator',
        ),
    ]
