# Generated by Django 4.0.8 on 2023-10-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('manager', 'Manager'), ('player', 'Player'), ('guardian', 'Guardian')], default='player', max_length=20),
        ),
    ]
