# Generated by Django 4.0.8 on 2023-10-30 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_manager',
        ),
    ]
