# Generated by Django 4.0.8 on 2023-11-05 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_guardian'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
