# Generated by Django 4.0.8 on 2023-11-03 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
        ('matches', '0002_alter_match_team1_alter_match_team2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='fields.booking'),
            preserve_default=False,
        ),
    ]
