# Generated by Django 4.0.8 on 2023-11-16 09:28

import apps.objections.models
import apps.objections.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objection',
            name='text',
        ),
        migrations.AlterField(
            model_name='objection',
            name='document',
            field=models.FileField(upload_to="objections/", validators=[apps.objections.validators.FileValidator(allowed_extensions='', allowed_mimetypes='', max_size=5242880)]),
        ),
    ]
