# Generated by Django 4.0.8 on 2023-11-16 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objections', '0002_remove_objection_text_objection_date_uploaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objection',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
