# Generated by Django 4.0.8 on 2023-11-16 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objections', '0003_objection_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objection',
            name='user',
        ),
    ]
