# Generated by Django 4.0.8 on 2023-11-16 10:47

import apps.objections.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objections', '0004_remove_objection_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objection',
            name='document',
            field=models.FileField(upload_to='objections', validators=[apps.objections.validators.FileValidator(allowed_extensions='', allowed_mimetypes='', max_size=5242880)]),
        ),
    ]
