# Generated by Django 4.0.8 on 2023-11-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objections', '0005_alter_objection_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='objection',
            name='name',
            field=models.CharField(default='first', max_length=255),
            preserve_default=False,
        ),
    ]
