# Generated by Django 4.0.8 on 2024-01-11 11:13

import apps.objections.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objections', '0008_alter_objection_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objection',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='objections', validators=[apps.objections.validators.FileValidator(allowed_extensions='', allowed_mimetypes='', max_size=5242880)]),
        ),
    ]
